### PR TITLE
Use prototype functions for client controllers

### PR DESCRIPTION
**Pull request by not-an-aardvark**
Given that the client controllers are considered as class constructors by angular, it will save some memory (and performance) to define prototype functions for them rather than redefining the functions for each instance.

### CODE REVIEW

**Comment by YaManicKill** [comment]
I think it would be better if we used ES6 classes. It's essentially the same thing, just much simpler to understand and nicer.

**Comment by not-an-aardvark** [comment]
> I think it would be better if we used ES6 classes.

It is using ES6 classes.

**Comment by YaManicKill** [comment]
Well, that'll teach me to actually look at the code rather than just read the description...

**Comment by not-an-aardvark** [comment]
Let me know if I should split these commits into separate PRs, since they're all independent of one another. For the time being I think I've spammed everyone's inbox enough for today, though.

**Comment by not-an-aardvark** [comment]
I fixed the merge conflicts, this should be ready to merge.

**Comment by YaManicKill** [comment]
YOLO :+1:

**Pull request merged**
