### PR TITLE
Add a form for updating a user's email address

### LINKED ISSUE #377: Allow editing of email address

### PR DESCRIPTION
**Pull request by not-an-aardvark**
fixes #377

### CODE REVIEW

**Comment by NotRaia** [comment]
Looks like it works fine, but right now nothing shows what the current email address is. I'd like to add this and rearrange the forms before merging.

**Comment by not-an-aardvark** [comment]
At one point I had it prefill the form with the current email address, but then I realized that there was no point to doing that because the user would always have to change it. Maybe we could have some separate info thing below the form field

**Comment by YaManicKill** [comment]
Have it put the current email as a place holder, so it shows it but it
disappears as soon as the user clicks.

**Comment by NotRaia** [comment]
Possibly, or we could do it like Facebook where it shows a list of your current information and you don't see the form until you click Edit.

**Comment by YaManicKill** [comment]
That's slightly different because it shows you your public profile and you
edit that there, the email address isn't part of your public profile. So...
Nah

**Comment by NotRaia** [comment]
I'm not talking about the public profile, I mean the account settings page. 

http://i.imgur.com/HDIjj4S.png

(don't worry, I do change my password, this is a throwaway)

**Pull request merged**
