### PR TITLE
Add themed error pages - fixes #51

### LINKED ISSUE #51: Themed error pages
(low-priority)

Eventually we'll probably want themed error pages. We should have one for:

* 403 Access denied
* 404 Not found
* 500 Internal server error

### PR DESCRIPTION
**Pull request by Kirzi**
403 Access Denied, 404 Not Found, 500 Internal Server Error - pages and image files

### CODE REVIEW

**Comment by YaManicKill** [comment]
Hey, @blackaurora, thanks for this, looks good.

Just 1 thing, can you take the css and put it in the stylesheet, and include the stylesheet in the pages. Other than that, looks good.

Also, can you squash the commits down to 1?

**Comment by not-an-aardvark** [comment]
The commits will be automatically squashed down to 1 anyway, won't they?

**Comment by YaManicKill** [comment]
Nah, we are currently doing merge commits, so they won't be squashed.

**Comment by not-an-aardvark** [comment]
LGTM

**Comment by YaManicKill** [comment]
Brilliant work, @Kirzi, thanks.

**Pull request merged**
