### PR TITLE
Add initial box viewing and creation.

### LINKED ISSUE #15: Creating boxes
Acceptance criteria:
Given that the user is identified
Ensure that new boxes can be created and assigned a name/description.

### PR DESCRIPTION
**Pull request by YaManicKill**
Still needs ability to set name and description for new box.

Fixes #15 and #21 

Also, still need to do some tests for the BoxController.

screenshot from 2016-02-14 18-09-11

### CODE REVIEW

**Comment by not-an-aardvark** [comment]
We may want to [scale these by screen size](https://i.gyazo.com/fd2a0b6faf51a4516bfd8aeea41f3118.png).

Also, do we want to allow boxes to have duplicate names? As far as UI is concerned I think it might be less confusing if the names have to be unique.

Final thing -- we should probably make sure the + button is always at the front if we stick with this box layout, because otherwise it [gets covered](https://i.gyazo.com/978c3ecb65a792085313391192df38b1.png) if there are too many boxes.

**Comment by YaManicKill** [comment]
1. Yeah, I've not looked into the framework too much as to how to do that
2. I think we do want to do that, because otherwise it gets complicated in terms of implementing that, especially as people are unlikely to actually try and do multiple with the same name, let's just not bother restricting that (because it would need to be unique on a per-user basis, not just overall)
3. Yeah, good plan.

**Comment by not-an-aardvark** [comment]
I think allowing duplicate box names will make the interface more complicated, and it'll be very hard to require unique names later on if people already have duplicates. For example, we might want to have a user-facing function like "move all of the uploaded pokemon into a specified box". People will want to select one of their box names to specify a box, but that won't work well if the box names can be duplicates. It will become even harder if we eventually want to allow boxes within other boxes.

**Comment by YaManicKill** [comment]
I disagree. As a user, I would be annoyed if I had to make box names
unique. Selecting a box for moving things to is easy with non unique names.
That's not a problem, just show them all in a list in the same order. I
don't see what the problem is there.

I see no reason to limit it, and it would be annoying to limit.

**Pull request merged**
