### PR TITLE
Toggleable dragging

### PR DESCRIPTION
**Pull request by not-an-aardvark**
There is now a button in the toolbar to enable dragging.

To do:

- [x] Find a better icon for the "enable dragging" button 
- [x] Give a stronger indication that the cards are draggable when dragging is enabled
- [x] Don't let image dragging interfere with the card dragging

### CODE REVIEW

**Comment by YaManicKill** [comment]
Maybe use https://material.angularjs.org/latest/demo/switch for the toggle?

**Comment by not-an-aardvark** [comment]
I was thinking it would be better if the icon gives a hint of what the dragging does, e.g. [this one](https://design.google.com/icons/#ic_swap_horiz).

At the moment the icon changes to a ["done checkmark"](https://design.google.com/icons/#ic_done) that you can use to indicate that you're finished dragging.

**Comment by YaManicKill** [comment]
I'm not sure that icon actually gives a good indication of what it is. When
you toggle edit mode on, we can just throw a toast up to say "Drag to
rearrange" and when we get bulk actions done, we can have that work as well.

It's just a toggle seems nicer and much more obvious that it's a ... well,
togglable thing.

**Comment by not-an-aardvark** [comment]
We can have a toast as well, but I think that having a good label is better than having an unlabelled switch. I think the fact that it changes to a checkmark is a good indication that it's a toggle.

I think the best icon would be something like [this](http://sweetclipart.com/multisite/sweetclipart/files/arrows_four.png), but google doesn't seem to have a material icon for it.

**Comment by YaManicKill** [comment]
Why the assumption that the switch would be unlabelled? It would have a
label. The problem with icons is that I really don't think anything
explains it well at all, and you are just trying to make something easy to
understand when you can just have an "Edit" toggle, and have other
indications afterwards how you can reorganise (we can have handles if that
would be best or whatever).

Icons don't always work well. I don't think the icons you have shown show
anything. And also the edit mode isn't just about moving things around.

**Comment by not-an-aardvark** [comment]
> And also the edit mode isn't just about moving things around.

I think there is a bit of confusion; the toggle isn't in the edit menu. [Demo](https://i.gyazo.com/58ac405289f68495598074479daa95ab.gif)

**Comment by YaManicKill** [comment]
On the irc, it was mentioned that the toggle was for edit mode, and the
edit mode would enable dragging. No?

**Comment by not-an-aardvark** [comment]
¯\\\_(ツ)_/¯

I think our current edit modal should only include editing permanent properties of the box. Stuff like enabling dragging should have a separate button outside of the edit modal.

**Comment by YaManicKill** [comment]
No, no. "Edit mode" is different from the "Edit modal". Edit mode is a mode
which allows you to drag and drop the pokemon, as well as do bulk actions
in the future (move to another box, change visibility).

**Comment by NotRaia** [comment]
What YMK said.

**Pull request merged**
