### PR TITLE
Handle profile-viewing errors more gracefully

### LINKED ISSUE #372: Handle profile-viewing errors gracefully
When you try to view someone's profile that doesn't exist, it looks like [this](https://i.gyazo.com/d52f5366995afb8413830d4beda411ed.png) and displays the "unexpected error" message. We should hide the template and suppress the error message if we're showing an error image anyway.

### PR DESCRIPTION
**Pull request by not-an-aardvark**
fixes #372

### CODE REVIEW

**Comment by YaManicKill** [comment]
I'm not really sure what this is doing.

**Comment by not-an-aardvark** [comment]
Previously it looked like [this](https://i.gyazo.com/d52f5366995afb8413830d4beda411ed.png) when you looked for a name that didn't exist, because our logic for hiding the templates was wrong.

Now it looks like [this](https://i.gyazo.com/4e86f8e1d016096c3ac84e4b8e67b89d.png) without the empty template.

**Comment by YaManicKill** [comment]
Are you missing some code? Because currently the profile.view.html does " ng-show="profile.data.name"" but you are now changing the username to be on profile.name, which implies to me that the user profile will never show.

**Comment by not-an-aardvark** [comment]
`profile.data.name` will get set [here](https://github.com/porygonco/porybox/blob/e223a454f3fa5663fd61938bd042d9f942830bd6/client/profile/profile.ctrl.js#L13) when the response from the server arrives.

**Comment by YaManicKill** [comment]
Looks fine. :+1: Merge when the build is passing.

**Pull request merged**
