### PR TITLE
Initial gen 7 changes

### LINKED ISSUE #541: Allow users to upload pk7s
So, a couple of things:

* We will add a new endpoint for pk7s (because the backend doesn't get the extension)
* We will remove support for pkxs
* We will change _rawpk6 to _rawFile
* We will add either generation or extension to the pokemon to distinguish between them
* pk6parse will get a new parsing mode

### PR DESCRIPTION
**Pull request by YaManicKill**
Not ready yet, but I thought I'd get this up just now.

Fixes #541

I have updated so that it uses the pk6parse gen 7 changes.

TODO:

- [ ] Remove the extra single-upload gen 7 call I made, because that won't work
- [ ] Either add a multi-upload for gen 7, or figure out a way to use them both on the same call
- [ ] Call the gen 7 calls when uploading .pk7s
- [ ] Wait for the pk6parse release

### CODE REVIEW

**Comment by YaManicKill** [comment]
Note that I have added a gen 7 single-upload call, which is silly as we will be removing it anyway. I will remove this soon.

**Comment by not-an-aardvark** [comment]
I think it would probably be best to support gen 7 in the existing multi-upload API, and have an extra field like `gen: 7` along with the binary data for each file. So it would look roughly like this:

```json
{
  "files": [
    {"visibility": "private", "box": "abcdef", "data": "Base64==", "gen": 6},
    {"visibility": "private", "box": "abcdef", "data": "Base64==", "gen": 7}
  ]
}
```

**Comment by YaManicKill** [comment]
Yeah. I had been thinking of a way to do it nicely but hadn't put much
thought into it. That's good, I'll do that (or you can, if you want). It
might be easiest to start this from scratch.

**Comment by YaManicKill** [comment]
I'm not sure how much more time I'll able to do to this before I move house, as time is getting really busy.

Thankfully, we move in 2 weeks, so after we have tidied up the house, I'll get some time to do this again.

However, because I'm not able to do it straight away, if anyone wants to take it over (if they have the time before I move and get set up) then feel free. The pk6parse PR just needs a few more tests of gen 7 stuff (checking some new moves/pokemon names/etc, hyper training, blue/pink marks) and I think the ribbon that @SnowPhoenix said he needed to do (is there anything else?). This PR should be re-written (probably from scratch) using what naa said, we need the images for everything other than items, and we need visualitations for hyper training and the new pink markings.

But if no one has picked it up by the time my office is ready in the new house, I'll get to it then.

**Comment by not-an-aardvark** [comment]
Closing in favor of https://github.com/porygonco/porybox/pull/618

**Pull request closed without merging**
