### PR TITLE
Update all angular stuff to 1.6.0 at the same time

### PR DESCRIPTION
**Pull request by YaManicKill**
Still needs an angular material update, which isn't out yet. It's broken with angular 1.6.0, but we needed to update all the angular stuff at once, not in separate PRs.

### CODE REVIEW

**Comment by not-an-aardvark** [comment]
It looks like the build is broken -- is that related to the angular stuff?

**Comment by YaManicKill** [comment]
Did you read my comment? We need to wait for angular material to update.

**Comment by not-an-aardvark** [comment]
I saw it, but again, the build is broken right now. We should probably fix that sooner rather than waiting for angular-material to upgrade, even if it means pinning things to 1.5 for the time being.

**Comment by YaManicKill** [comment]
Oh wait, you mean on master. I thought you meant this branch. See, this is
why I like pinning things always.

**Comment by YaManicKill** [comment]
Looks like the 1.6.1 fixes these issues. Will fix up this pr this week sometime.

**Comment by YaManicKill** [comment]
@not-an-aardvark I don't think I'm causing problems with using the old angular-mocks with new angular, as everything is working. I detailed the issues with the new angular-mock on #586 

Can you just give this a quick review before I merge?

**Comment by YaManicKill** [comment]
Thanks, @not-an-aardvark

**Pull request merged**
