### PR TITLE
Add Apache license

### PR DESCRIPTION
**Pull request by not-an-aardvark**
Seems like we forgot to add a license file until now.

To avoid complications later on, it would be good if everyone who has contributed could comment here saying that they're okay with adding this.

@NotRaia @YaManicKill @TheSonAlsoRises @SnowPhoenix @Kirzi

### CODE REVIEW

**Comment by Kirzi** [comment]
Fine with me.

**Comment by TheSonAlsoRises** [comment]
I am okay with the Apache license.

**Comment by YaManicKill** [comment]
I am good with that.

**Comment by NotRaia** [comment]
Sounds good to me.

**Comment by SnowPhoenix** [comment]
Per our discussion, I'm fine with this. 👍

**Comment by YaManicKill** [comment]
Merged as all contributors gave their permission. We are Apache licensed, all. Congrats.

**Pull request merged**
